-- Generated by Oracle SQL Developer Data Modeler 19.4.0.350.1424
--   at:        2020-04-30 11:04:42 EEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE film (
    film_id         INTEGER NOT NULL,
    budget          FLOAT,
    homepage        VARCHAR2(200),
    original_title  VARCHAR2(200),
    release_date    DATE,
    runtime         FLOAT
);

ALTER TABLE film ADD CONSTRAINT film_pk PRIMARY KEY ( film_id );

CREATE TABLE film_company (
    film_film_id           INTEGER NOT NULL,
    production_company_id  INTEGER NOT NULL
);

ALTER TABLE film_company ADD CONSTRAINT relation_5_pk PRIMARY KEY ( film_film_id,
                                                                    production_company_id );

CREATE TABLE film_country (
    film_film_id           INTEGER NOT NULL,
    production_country_id  VARCHAR2(2) NOT NULL
);

ALTER TABLE film_country ADD CONSTRAINT relation_6_pk PRIMARY KEY ( film_film_id,
                                                                    production_country_id );

CREATE TABLE film_genres (
    film_film_id     INTEGER NOT NULL,
    genres_genre_id  INTEGER NOT NULL
);

ALTER TABLE film_genres ADD CONSTRAINT relation_9_pk PRIMARY KEY ( film_film_id,
                                                                   genres_genre_id );

CREATE TABLE film_languages (
    film_film_id                 INTEGER NOT NULL,
    spoken_language_language_id  VARCHAR2(2) NOT NULL
);

ALTER TABLE film_languages ADD CONSTRAINT relation_7_pk PRIMARY KEY ( film_film_id,
                                                                      spoken_language_language_id );

CREATE TABLE genres (
    genre_id  INTEGER NOT NULL,
    genre     VARCHAR2(100)
);

ALTER TABLE genres ADD CONSTRAINT genres_pk PRIMARY KEY ( genre_id );

CREATE TABLE production_company (
    company_id    INTEGER NOT NULL,
    company_name  VARCHAR2(100)
);

ALTER TABLE production_company ADD CONSTRAINT production_company_pk PRIMARY KEY ( company_id );

CREATE TABLE production_country (
    country_id    VARCHAR2(2) NOT NULL,
    country_name  VARCHAR2(100)
);

ALTER TABLE production_country ADD CONSTRAINT production_country_pk PRIMARY KEY ( country_id );

CREATE TABLE spoken_language (
    language_id    VARCHAR2(2) NOT NULL,
    language_name  VARCHAR2(100)
);

ALTER TABLE spoken_language ADD CONSTRAINT spoken_language_pk PRIMARY KEY ( language_id );

ALTER TABLE film_company
    ADD CONSTRAINT production_company_rel FOREIGN KEY ( production_company_id )
        REFERENCES production_company ( company_id );

ALTER TABLE film_country
    ADD CONSTRAINT production_country_rel FOREIGN KEY ( production_country_id )
        REFERENCES production_country ( country_id );

ALTER TABLE film_company
    ADD CONSTRAINT relation_5_film_fk FOREIGN KEY ( film_film_id )
        REFERENCES film ( film_id );

ALTER TABLE film_country
    ADD CONSTRAINT relation_6_film_fk FOREIGN KEY ( film_film_id )
        REFERENCES film ( film_id );

ALTER TABLE film_languages
    ADD CONSTRAINT relation_7_film_fk FOREIGN KEY ( film_film_id )
        REFERENCES film ( film_id );

ALTER TABLE film_languages
    ADD CONSTRAINT relation_7_spoken_language_fk FOREIGN KEY ( spoken_language_language_id )
        REFERENCES spoken_language ( language_id );

ALTER TABLE film_genres
    ADD CONSTRAINT relation_9_film_fk FOREIGN KEY ( film_film_id )
        REFERENCES film ( film_id );

ALTER TABLE film_genres
    ADD CONSTRAINT relation_9_genres_fk FOREIGN KEY ( genres_genre_id )
        REFERENCES genres ( genre_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             9
-- CREATE INDEX                             0
-- ALTER TABLE                             17
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
